---
language: python

services:
  - docker

env:
  global:
    - ROLE_NAME=pirat_tool

install:
  - python -m pip -q install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-role-pirat-tool dhach.$ROLE_NAME
  - cd dhach.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
