---
# tasks file for ansible-role-pirat-tool

- include_tasks: preflight.yml

- name: ensure deployment directories exist
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ pirat_deployment_user }}"
    group: "{{ pirat_deployment_group }}"
    mode: 0750
    recurse: true
  loop:
    - "{{ pirat_deployment_directory }}"
    - "{{ pirat_deployment_directory }}/database_init"
  loop_control:
    loop_var: dir

- name: get database init script
  get_url:
    url: https://raw.githubusercontent.com/COVID19-PIRAT/backend/master/init.sql
    dest: "{{ pirat_deployment_directory }}/database_init/init.sql"
    mode: 0644
  when: pirat_postgres_use_docker

- name: deploy docker-compose.yml
  template:
      dest: "{{ pirat_deployment_directory }}/docker-compose.yml"
      src: docker-compose.yml.j2
      owner: "{{ pirat_deployment_user }}"
      group: "{{ pirat_deployment_group }}"
      mode: 0640
      validate: docker-compose -f %s config -q
      output_encoding: utf-8
      backup: true

- name: pull images to speed up service start
  command:
      cmd: "docker-compose -f {{ pirat_deployment_directory }}/docker-compose.yml pull"
## we do not use the ansible module docker_compose, because this requires an additional python library on the target

- include_tasks: systemd.yml
